---
spec/spec_helper.rb:
  mock_with: ':rspec'
Gemfile:
  optional:
    ':development':
      - gem: 'puppet-resource_api'
      - gem: 'pry'
      - gem: facter
        version: '> 4.0.43'
        platforms: mri_25
